# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79174065ea2b586365487130075da1900670ba9e1dceba4917ca4c805f98c64b775b236e4c426fb5a9e2ef9fc264fb642ccbef7e3b5dee901921bf536043879

test:
  secret_key_base: 2289f54724fd1d8a3de0b531806cf1e0888a630707843bd0e56f3e872b4eafdfeae0e780721c2e85c04f1af63c3cd338ec7da978c7828bab1b30e4201df6599f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
